import ContextController = require('../core/ContextController');
import ContextMonitor = require('../core/ContextMonitor');
import ContextListener = require('../core/ContextListener');
import DrawElements = require('../dfx/DrawElements');
import IDrawList = require('../scene/IDrawList');
import IMesh = require('../dfx/IMesh');
import IUnknown = require('../core/IUnknown');
import UniformData = require('../core/UniformData');
declare class WebGLRenderer implements ContextController, ContextMonitor, IUnknown {
    private _canvas;
    private _kahuna;
    private _renderer;
    private _canvasId;
    private _refCount;
    private _uuid;
    constructor(canvas?: HTMLCanvasElement, canvasId?: number, attributes?: WebGLContextAttributes);
    addContextListener(user: ContextListener): void;
    addRef(): number;
    canvasId: number;
    gl: WebGLRenderingContext;
    createDrawElementsMesh(elements: DrawElements, mode?: number, usage?: number): IMesh;
    canvas: HTMLCanvasElement;
    release(): number;
    removeContextListener(user: ContextListener): void;
    render(drawList: IDrawList, ambients: UniformData): void;
    setClearColor(color: number, alpha?: number): void;
    setSize(width: number, height: number, updateStyle?: boolean): void;
    start(): void;
    stop(): void;
}
export = WebGLRenderer;
