import ContextController = require('../core/ContextController');
import ContextManager = require('../core/ContextManager');
import ContextMonitor = require('../core/ContextMonitor');
import ContextListener = require('../core/ContextListener');
import ContextRenderer = require('../renderers/ContextRenderer');
import DrawElements = require('../dfx/DrawElements');
import IContextCommand = require('../core/IContextCommand');
import IDrawList = require('../scene/IDrawList');
import IMesh = require('../dfx/IMesh');
import Shareable = require('../utils/Shareable');
import UniformData = require('../core/UniformData');
declare class WebGLRenderer extends Shareable implements ContextController, ContextMonitor, ContextRenderer {
    private _canvas;
    private _canvasId;
    private _kahuna;
    private _renderer;
    constructor(canvas?: HTMLCanvasElement, canvasId?: number, attributes?: WebGLContextAttributes);
    destructor(): void;
    addContextListener(user: ContextListener): void;
    canvasId: number;
    createDrawElementsMesh(elements: DrawElements, mode?: number, usage?: number): IMesh;
    canvas: HTMLCanvasElement;
    contextFree(canvasId: number): void;
    contextGain(manager: ContextManager): void;
    contextLoss(canvasId: number): void;
    gl: WebGLRenderingContext;
    prolog(): void;
    pushProlog(command: IContextCommand): void;
    pushStartUp(command: IContextCommand): void;
    removeContextListener(user: ContextListener): void;
    render(drawList: IDrawList, ambients: UniformData): void;
    start(): void;
    stop(): void;
}
export = WebGLRenderer;
