import Cartesian3 = require('../math/Cartesian3');
import GeometricElement = require('../math/GeometricElement');
import Matrix4 = require('../math/Matrix4');
import Vector3 = require('../math/Vector3');
declare class Quaternion implements GeometricElement<Quaternion, Quaternion> {
    private _x;
    private _y;
    private _z;
    private _w;
    onChangeCallback: () => void;
    constructor(x?: number, y?: number, z?: number, w?: number);
    x: number;
    y: number;
    z: number;
    w: number;
    add(element: Quaternion): Quaternion;
    addVectors(a: Quaternion, b: Quaternion): Quaternion;
    set(x: number, y: number, z: number, w: number): Quaternion;
    clone(): Quaternion;
    conjugate(): Quaternion;
    copy(quaternion: Quaternion): Quaternion;
    divideScalar(scalar: number): Quaternion;
    dot(v: Quaternion): number;
    exp(): Quaternion;
    inverse(): Quaternion;
    magnitude(): number;
    multiply(q: Quaternion): Quaternion;
    multiplyQuaternions(a: Quaternion, b: Quaternion): Quaternion;
    multiplyScalar(scalar: number): Quaternion;
    normalize(): Quaternion;
    onChange(callback: () => void): Quaternion;
    quaditude(): number;
    setFromAxisAngle(axis: Cartesian3, angle: number): Quaternion;
    setFromRotationMatrix(m: Matrix4): Quaternion;
    setFromUnitVectors(vFrom: Vector3, vTo: Vector3): Quaternion;
    slerp(qb: Quaternion, t: number): Quaternion;
    sub(rhs: Quaternion): Quaternion;
    equals(quaternion: Quaternion): boolean;
    fromArray(array: number[], offset?: number): Quaternion;
    toArray(array?: number[], offset?: number): number[];
    static slerp(qa: Quaternion, qb: Quaternion, qm: Quaternion, t: number): Quaternion;
}
export = Quaternion;
