YUI.add("yuidoc-meta", function(Y) {
   Y.YUIDoc = { meta: {
    "classes": [
        "ArrowBuilder",
        "ArrowOptions",
        "AttribLocation",
        "AttribMetaInfo",
        "AttribMetaInfos",
        "BarnGeometry",
        "BoxBuilder",
        "BoxComplex",
        "BoxMesh",
        "Cartesian1",
        "Cartesian2",
        "Cartesian3",
        "Cartesian4",
        "Color",
        "Complex",
        "ContextAttributesLogger",
        "ContextListener",
        "CuboidMesh",
        "CylinderArgs",
        "EIGHTLogger",
        "ElementArray",
        "ElementBuffer",
        "EllipsoidMesh",
        "Face3",
        "Frustum",
        "Geometry",
        "HTMLScriptsMaterial",
        "KleinBottleGeometry",
        "Line3",
        "Material",
        "Matrix4",
        "Matrix<M>",
        "Mesh",
        "MeshNormalMaterial",
        "Mutable",
        "Perspective",
        "PerspectiveCamera",
        "Point3",
        "Scene",
        "ShaderVariableDecl",
        "Shareable",
        "Simplex",
        "Spinor3",
        "Symbolic",
        "UniformLocation",
        "UniformMetaInfos",
        "UniformProvider",
        "Vector1",
        "Vector2",
        "Vector3",
        "Vector4",
        "VersionLogger",
        "View",
        "WebGLClear",
        "WebGLClearColor",
        "WebGLEnable",
        "WindowAnimationRunner",
        "createView"
    ],
    "modules": [
        "EIGHT"
    ],
    "allModules": [
        {
            "displayName": "EIGHT",
            "name": "EIGHT"
        }
    ]
} };
});