YUI.add("yuidoc-meta", function(Y) {
   Y.YUIDoc = { meta: {
    "classes": [
        "AmbientLight",
        "ArrowBuilder",
        "ArrowOptions",
        "AttributeMetaInfo",
        "AttributeMetaInfos",
        "AttributeProvider",
        "BoxBuilder",
        "BoxMesh",
        "Cartesian3",
        "Color",
        "Color\nWARNING: In many object-oriented designs, types representing values are completely immutable.\nIn a graphics library where data changes rapidly and garbage collection might become an issue,\nit is common to use reference types, such as in this design. This mutability can lead to\ndifficult bugs because it is hard to reason about where a color may have changed.",
        "CuboidMesh",
        "DefaultUniformProvider",
        "DirectionalLight",
        "DrawMode",
        "Drawable",
        "ElementArray",
        "EllipsoidMesh",
        "Face3",
        "Frustum",
        "Geometry",
        "GeometryAdapter",
        "KleinBottleGeometry",
        "Line3",
        "LinearPerspectiveCamera",
        "LocalModel",
        "Matrix4",
        "Model",
        "Mutable",
        "Node",
        "Node3D",
        "Point3",
        "PointLight",
        "Renderer",
        "RenderingContextUser",
        "ShaderAttributeLocation",
        "ShaderAttributeLocation.",
        "ShaderProgram",
        "ShaderUniformLocation",
        "ShaderVariableDecl",
        "Spinor3",
        "Symbolic\nCanonical variable names, which act as semantic identifiers.",
        "TreeModel",
        "UniformColor",
        "UniformFloat",
        "UniformMetaInfo",
        "UniformMetaInfos",
        "UniformProvider",
        "UniformSpinor3",
        "UniformVariable",
        "UniformVector3",
        "Vector3",
        "View",
        "Viewport",
        "WebGLRenderer",
        "WindowAnimationRunner",
        "frustum",
        "perspective",
        "view"
    ],
    "modules": [
        "d8"
    ],
    "allModules": [
        {
            "displayName": "d8",
            "name": "d8"
        }
    ]
} };
});